### ISSUE TITLE
Ladder Crash on Update 6 Mac OS M2

### ISSUE THREAD

**Issue by maalgorium** [TobbyTheBobby/TimberbornMods#19]
The ladder mod crashes on startup for Update 6 on MacOS 14.5 on M2. The mod starts up fine under Rosetta ("MacOS Workaround" launch type). 

The key line in the logs appears to be:

`ERROR: Shader Hidden/Universal Render Pipeline/DBufferClear shader is not supported on this GPU (none of subshaders/fallbacks are suitable)`

Great mod. A must have for me.

**Comment by maalgorium** [comment]
Sure. I'll attach some logs.
[1 Exception 2024-07-25-17h09m27s.txt](https://github.com/user-attachments/files/16391519/1.Exception.2024-07-25-17h09m27s.txt)
[2 Player log 2024-07-25-17h09m27s.txt](https://github.com/user-attachments/files/16391533/2.Player.log.2024-07-25-17h09m27s.txt)

**Comment by KnatteAnka** [comment]
So are you running the game with Rosetta and it does not work or what do you mean?

Because Harmony is not supported on Macos if its in arm. 
So to get it to work it needs Rosetta. 
It has noting to do with ladder its a req for using harmony

see Mac OS problems
https://mod.io/g/timberborn/r/troubleshooting-mod-setup

**Comment by KnatteAnka** [comment]
the info that Harmony needs Rosetta is also forwarded to author of Harmony

**Comment by maalgorium** [comment]
When I run in arm mode it doesn't work. Sorry, didn't realize that that was expected behavior. In update 5 I ran with the same  startup configuration with this mod and it worked. Maybe the default startup was Rosetta in update 5?
